#!/bin/bash


echo "Cleaning..."

rm -rf mphys.html
rm -rf __*
rm -rf reports
rm -rf postProcessing
rm -rf constant/extendedFeatureEdgeMesh
rm -rf constant/triSurface
rm -rf *.bin *.info *.dat *.xyz *.stl
rm -rf processor* 0.0000*
rm -rf {1..9}*

echo "Done!"
